%%%%%%%% RP-1 Manned Mission Resource Calculator %%%%%%%%
% Made by Jordan Langford
% Licensed under MIT License
% Version 1

% If you would like to do an apollo style water filling fuel cells scheme,
% simply add more water volume to your tanks and leave them empty. The
% codes automatically sets a minimum volume of water and other resources as
% a safety margin, but these can be expanded if you want a higher safety
% margin and are running processes that will fill them.

% The electrical calculations are pretty fast and loose. RTG decay and
% solar panel degradation is not currently accounted for, and I generally
% assume that most users won't be mixing RTGs and solar panels with fuel
% cells, though the code will produce an estimate assuming no degradation
% or decay if you want, which may suffice for short trips. It may be
% advisable to use the furthest distance from the sun, most degraded solar
% panel predicted output for mission calculations, though the output will
% be conservative. Hopefully this will suffice as a starting point for
% extremely weight-restricted missions to iteratively simulate and
% optimize.

% This code currently doesn't support electrolysis, sabatier process,
% methane pyrolysis, or RWGS because their use cases confuse me (sorry)
% and, in many cases, coding them using linear relationships becomes
% difficult due to the cyclic nature of their combined systems. The cycles
% make it difficult to set the rate-limiting steps and determine an output.

% This code does not account for boil off.

% If I did this code again, I'd use symbolic math to make the rates
% functions of time, then integrate to find the total resources required,
% but it's too late for that. 

%% Setup

clc;close all

% this section determines if the import variable already exists, and if so,
% asks the user if they want to import the last settings. If you want to
% skip the question and automatically import the last settings, uncomment
% the first line and comment out the questdlg line. If the old settings are
% not imported, the import variable is cleared using a function located at
% the bottom of the code. If a user desires to edit the defaults upon not
% importing prior settings, they should change the values in the
% importreset function.

if exist("import","var")
%    keep = "Yes";
    keep = questdlg("Would you like to import the last used settings?","Menu","Yes","No","Yes");
    if keep == "Yes"
        clearvars -except import
    else
        clear
        import = importreset(import);
    end
else
    clear
    import = importreset(import);
end

%% Kerbal Resources

% This section uses the rates per kerbal given by the RP-1 creators in the
% kerbalism config to establish the rates of resource consumption per
% kerbal per second.

% pk = per kerbal per second

pk.food = 5.84928/24/3600;                                     % food/sec
pk.waste = 2.1917568666335128/24/3600;                         % waste/sec
pk.water = 3.87072/24/3600;                                    % water/sec
pk.wastewater = 3.8514629877106067/24/3600;                    % wastewater/sec
pk.oxygen = 591.84/24/3600;                                    % O2/sec
pk.wasteatm = 423.44921605648228/24/3600*0.006216/0.00615384;  % wasteatmo/sec
% ^ measured from CO2 production and converted since there's not a waste atmosphere tank

%% Resoure Densities

% This section inputs mass/liter of resources. These values were obtained
% by filling a tank with 1 Megaliter of each resource in game to obtain the
% change in mass and relate ton/megaliter to kg/liter.

density.food = 0.281;
density.water = 1;
density.oxygen = 0.00141;
density.nitrogen = 0.001251;
density.lioh = 1.46;
density.KO3 = 2.14;
density.lox = 1.141;
density.lh2 = 0.07085;
density.hydrogen = 0.00009;
density.liqmeth = 425.637;
density.batt = 0.00144;

%% Scubber conversion rates

% This section once again uses the RP-1 kerbalism config to establish
% resource conversion rates. KW was selected as a base in order to account
% for unusual setups in which users intentionally do not provide sufficient
% processes to fully process a resource... so it's mostly to produce robust
% code for people doing weird things.

% I'm aware that a kw-sec is a kilojoule, it's just easier for me this way
% since we'll be dealing mostly in kw.

rate.scrub.lion2.wasteatm = 0.012432/0.1;     % wasteatm/kw-sec
rate.scrub.lion2.LiH2 = 0.00001189/0.1;       % LiH2/kw-sec
rate.scrub.lion2.waste = 0.00003234/0.1;      % waste/kw-sec

rate.scrub.lion.wasteatm = 0.006216/0.1;      % wasteatm/kw-sec
rate.scrub.lion.LiH2 = 0.00001189/0.1;        % LiH2/kw-sec
rate.scrub.lion.waste = 0.00001617/0.1;       % waste/kw-sec

rate.scrub.vac.wasteatm = 0.006216/0.15;      % wasteatm/kw-sec
rate.scrub.vac.CO2 = 0.0055944/0.15;          % CO2/kw-sec

rate.scrub.adv.wasteatm = 0.006216/0.1;       % wasteatm/kw-sec
rate.scrub.adv.CO2 = 0.00615384/0.1;          % CO2/kw-sec

rate.scrub.pot.wasteatm = 0.00453827/0.01;    % wasteatm/kw-sec
rate.scrub.pot.KO3 = 0.00001337/0.01;         % KO3/kw-sec
rate.scrub.pot.O2 = 0.006851/0.01;            % O2/kw-sec
rate.scrub.pot.waste = 0.000020859375/0.01;   % waste/kw-sec

%% Pressurization rate

% see prior comments

% rate.leak = 0.35/70;                            % milliliters/m^2/s
% not currently used. It's easier to get the leak rate from the game.

%% Processing rates

% see prior comments

rate.proc.rec.wastewater = 0.00004458/0.1;                 % wastewater/kw-sec
rate.proc.rec.water = 0.0000336/0.1;                       % water/kw-sec
rate.proc.rec.ammonia = 0.00000104/0.1;                    % ammonia/kw-sec

rate.proc.inc.waste = 0.0001082667/0.005;                  % waste/kw-sec
rate.proc.inc.O2 = 0.1589194249/0.005;                     % O2/kw-sec
rate.proc.inc.CO2 = 0.1497439605/0.005;                    % CO2/kw-sec
rate.proc.inc.water = 0.0000131259/0.005;                  % water/kw-sec

rate.proc.electrolysis.water = 0.000011248/0.178486;       % water/kw-sec
rate.proc.electrolysis.H2 = 0.014/0.178486;                % H2/kw-sec
rate.proc.electrolysis.O2 = 0.007/0.178486;                % O2/kw-sec

rate.proc.sabatier.CO2 = 0.0172683775/0.8;                 % CO2/kw-sec
rate.proc.sabatier.H2 = 0.064721246/0.8;                   % H2/kw-sec
rate.proc.sabatier.water = 0.0000259988/0.8;               % H2O/kw-sec
rate.proc.sabatier.liqmeth = 0.0000271941/0.8;             % LCH4/kw-sec

rate.proc.methpyro.liqmeth = 0.0000271941/0.7;             % LCH4/kw-sec
rate.proc.methpyro.H2 = 0.00447458318/0.7;                 % H2/kw-sec

rate.proc.bioreactor.CO2 = 0.0003642625469/0.016;          % CO2/kw-sec
rate.proc.bioreactor.wastewater = 0.000001736111111/0.016; % wastewater/kw-sec
rate.proc.bioreactor.O2 = 0.0006932114657/0.016;           % O2/kw-sec
rate.proc.bioreactor.water = 0.000001425957342/0.016;      % water/kw-sec
rate.proc.bioreactor.food = 0.0000001853274065/0.016;      % food/kw-sec

rate.proc.regpyro.reg = 0.0000027667584/1.444247885;       % regolith/kw-sec
rate.proc.regpyro.O2 = 0.007/1.444247885;                  % O2/kw-sec

rate.proc.moxie.CO2 = 0.01409853921/0.24;                  % CO2/kw-sec
rate.proc.moxie.O2 = 0.007092198582/0.24;                  % O2/kw-sec

rate.proc.RWGS.CO2 = 0.8433582486/38.0630714;              % CO2/kw-sec
rate.proc.RWGS.H2 = 1.044616251/38.0630714;                % H2/kw-sec
rate.proc.RWGS.lqdmeth = 0.0008827766639/38.0630714;       % LCH4/kw-sec
rate.proc.RWGS.lox = 0.001185518392/38.0630714;            % LOX/kw-sec

rate.proc.lox.lox = 0.0000154599/0.00467;                  % LOX/kw-sec
rate.proc.lox.O2 = 0.0125104279/0.00467;                   % LH2/kw-sec

%% Fuel Cell Rates

% see prior comments

rate.fc.gem.lox = 0.00008282;                     % LOX/kw-sec
rate.fc.gem.lh2 = 0.000168065;                    % LH2/kw-sec
rate.fc.gem.water = 0.000106416;                  % water/kw-sec

rate.fc.apollo.lox = 0.00007247;                  % LOX/kw-sec
rate.fc.apollo.lh2 = 0.000147057;                 % LH2/kw-sec
rate.fc.apollo.water = 0.000093114;               % water/kw-sec

rate.fc.aes.O2 = 0.0604438;                       % O2/kw-sec
rate.fc.aes.H2 = 0.119453;                        % H2/kw-sec
rate.fc.aes.water = 0.0000959646;                 % water/kw-sec

rate.fc.soyuz.lox = 0.00008282;                   % lox/kw-sec
rate.fc.soyuz.lh2 = 0.000168065;                  % lh2/kw-sec
rate.fc.soyuz.water = 0.000106416;                % water/kw-sec

rate.fc.shuttle.lox = 0.0000654357;               % lox/kw-sec
rate.fc.shuttle.lh2 = 0.0001327828;               % lh2/kw-sec
rate.fc.shuttle.water = 0.0000840758;             % water/kw-sec

rate.fc.ch4.lox = 0.0000840087;                  % lox/kw-sec
rate.fc.ch4.liqmeth = 0.0000564461;              % lch4/kw-sec
rate.fc.ch4.water = 0.0000539642;                % water/kw-sec
rate.fc.ch4.CO2 = 0.0337858;                     % CO2/kw-sec

%% Misc Rates

% taken from in game water consumption number, if anyone could verify this
% rate somehow I'd appreciate it.

rate.comfort.shower.water = 0.0000579;              % water/sec
rate.comfort.shower.wastewater = 0.0000579;         % wastewater/sec
% wastewater per second assumed by checking kerbalism's change in produced
% water when turning on showers and dividing by the conversion rate of
% water/wastewater.

%% User Setup

% This section renders the gui and provides editable boxes saves as fields
% within the structure "setup" and waits for the user to click the Accept
% button. If data was imported, the fields will be filled in wih old data.
% Otherwise, the defaults will be used.

pause(0.25)

setup.f = figure('Name','Basic Mission Profile Setup',...
                 'NumberTitle','off',...
                 'units','inches',...
                 'position',[5,2,8,5]);

setup.q1 = uicontrol('style','text',...
                     'string','Number of Kerbals',...
                     'units','inches',...
                     'position',[1/4,18/4,3/4,1/4]);

setup.kerbal_num = uicontrol('style','edit',...
                             'String',import.kerbal_num,...
                             'units','inches',...
                             'position',[4/4,18/4,1/4,1/4]);

setup.atmopanel = uipanel("title","Pressurization and Scrubbing",...
                          "titleposition",'centertop',...
                          'units','inches',...
                          'position',[3/16,54/16,32/16,17/16]);

setup.q2 = uicontrol('style','text',...
                     'string','Scrubber',...
                     'units','inches',...
                     'position',[1/4,16/4,3/4,1/4]);

setup.scrub = uicontrol('style','popupmenu',...
                     'String',["Adv. Vac","Vac","KO3","LiOH","LiOH, 2 day"],...
                     'units','inches',...
                     'Position',[5/16,53/16,3/4,3/4],...
                     'value',import.scrub);

setup.q3 = uicontrol('style','text',...
                     'string','Pressurization',...
                     'units','inches',...
                     'Position',[5/4,16/4,3/4,1/4]);

setup.press = uicontrol('style','popupmenu',...
                     'String',["Nitrogen","Oxygen","None"],...
                     'units','inches',...
                     'Position',[20/16,53/16,3/4,3/4],...
                     'Value',import.press);

setup.rec = uicontrol('style','togglebutton',...
                    'String','Water recycled',...
                    'units','inches',...
                    'Position',[19/8,18/4,4/4,1/4],...
                    'Value',import.rec);

setup.q4 = uicontrol('style','text',...
                     'string','KW Total',...
                     'units','inches',...
                     'Position',[19/8,33/8,1/2,1/4]);

setup.kwrec = uicontrol("Style","edit",...
                        "String",import.kwrec,...
                        'Units','inches',...
                        'Position',[24/8,67/16,3/8,1/4]);

setup.green = uicontrol('style','togglebutton',...
                     'string','Greenhouse in use',...
                     'units','inches',...
                     'Position',[59/16,18/4,9/8,1/4],...
                     'Value',import.green);

setup.q5 = uicontrol('style','text',...
                     'string','KW Total',...
                     'units','inches',...
                     'Position',[30/8,33/8,1/2,1/4]);

setup.kwgreen = uicontrol('style','edit',...
                           'string',import.kwgreen,...
                           'units','inches',...
                           'position',[69/16,67/16,3/8,1/4]);

setup.q6 = uicontrol('style','text',...
                     'String','# of Showers Running',...
                     'units','inches',...
                     'Position',[19/8,59/16,4/4,1/4]);

setup.showers = uicontrol('Style','edit',...
                          'string',import.showers,...
                          'units','inches',...
                          'position',[22/8,27/8,1/4,1/4]);

setup.elecpanel = uipanel("title","Electrical",...
                          "titleposition",'centertop',...
                          'units','inches',...
                          'position',[39/8,9/8,10/4,61/16]);

setup.elec = uicontrol('Style','togglebutton',...
                       'String','Calculate Electrical',...
                       'units','inches',...
                       'position',[23/4,18/4,4/4,1/4],...
                       'Value',import.elec);

setup.q71 = uicontrol('Style','text',...
                      'String','% time in shadow',...
                      'units','inches',...
                      'position',[22/4,67/16,4/4,1/4]);

setup.shadow = uicontrol('Style','edit',...
                         'String',import.shadow,...
                         'units','inches',...
                         'position',[26/4,17/4,2/4,1/4]);

setup.q72 = uicontrol('Style','text',...
                      'String','Average exposure %',...
                      'units','inches',...
                      'position',[43/8,63/16,9/8,1/4]);

setup.exposure = uicontrol('Style','edit',...
                           'String',import.exposure,...
                           'units','inches',...
                           'position',[26/4,16/4,2/4,1/4]);

setup.q73 = uicontrol('Style','text',...
                      'String','KW Solar Power',...
                      'units','inches',...
                      'position',[22/4,59/16,4/4,1/4]);

setup.solar = uicontrol('Style','edit',...
                        'String',import.solar,...
                        'units','inches',...
                        'position',[26/4,15/4,2/4,1/4]);

setup.q74 = uicontrol('Style','text',...
                      'String','KW RTG Power',...
                      'Units','inches',...
                      'Position',[88/16,55/16,4/4,1/4]);

setup.rtg = uicontrol("Style",'edit',...
                          'String',import.rtg,...
                          'Units','inches',...
                          'Position',[26/4,14/4,2/4,1/4]);

setup.q75 = uicontrol('Style','text',...
                      'String','KW Nuclear Power',...
                      'units','inches',...
                      'position',[87/16,51/16,4/4,1/4]);

setup.nuclear = uicontrol('Style','edit',...
                         'String',import.nuclear,...
                         'units','inches',...
                         'position',[26/4,13/4,2/4,1/4]);

setup.q76 = uicontrol('Style','text',...
                      'String','Avg KW Consumed',...
                      'units','inches',...
                      'position',[87/16,47/16,4/4,1/4]);

setup.kw = uicontrol('Style','edit',...
                      'String',import.kw,...
                      'units','inches',...
                      'position',[26/4,12/4,2/4,1/4]);

setup.q77 = uicontrol('style','text',...
                      'String','KW of Gemini Fuel cells',...
                      'units','inches',...
                      'Position',[83/16,43/16,5/4,1/4]);

setup.gemini = uicontrol('Style','edit',...
                         'String',import.gemini,...
                         'units','inches',...
                         'position',[26/4,11/4,2/4,1/4]);

setup.q78 = uicontrol('style','text',...
                      'String','KW of Apollo Fuel cells',...
                      'units','inches',...
                      'Position',[83/16,39/16,5/4,1/4]);

setup.apollo = uicontrol('Style','edit',...
                         'String',import.apollo,...
                         'units','inches',...
                         'position',[26/4,10/4,2/4,1/4]);

setup.q79 = uicontrol('style','text',...
                      'String','KW of AES Fuel cells',...
                      'units','inches',...
                      'Position',[84/16,35/16,5/4,1/4]);

setup.aes = uicontrol('Style','edit',...
                       'String',import.aes,...
                       'units','inches',...
                       'position',[26/4,9/4,2/4,1/4]);

setup.q710 = uicontrol('style','text',...
                      'String','KW of Soyuz Fuel cells',...
                      'units','inches',...
                      'Position',[83/16,31/16,5/4,1/4]);

setup.soyuz = uicontrol('Style','edit',...
                        'String',import.soyuz,...
                        'units','inches',...
                        'position',[26/4,8/4,2/4,1/4]);

setup.q711 = uicontrol('style','text',...
                      'String','KW of Shuttle Fuel cells',...
                      'units','inches',...
                      'Position',[83/16,27/16,5/4,1/4]);

setup.shuttle = uicontrol('Style','edit',...
                          'String',import.shuttle,...
                          'units','inches',...
                          'position',[26/4,7/4,2/4,1/4]);

setup.q712 = uicontrol('style','text',...
                      'String','KW of CH4 Fuel cells',...
                      'units','inches',...
                      'Position',[84/16,23/16,5/4,1/4]);

setup.ch4 = uicontrol('Style','edit',...
                      'String',import.ch4,...
                      'units','inches',...
                      'position',[26/4,6/4,2/4,1/4]);

setup.q713 = uicontrol('style','text',...
                      'String','Interplanetary Transfer Time',...
                      'units','inches',...
                      'Position',[159/32,19/16,12/8,1/4]);

setup.transtime = uicontrol('Style','edit',...
                            'String',import.transtime,...
                            'units','inches',...
                            'position',[26/4,5/4,2/4,1/4]);

% setup.decay = uicontrol('Style','checkbox',...
%                         'String','Decaying RTGs in Use',...
%                         'Units','inches',...
%                         'Position',[22/4,19/16,12/8,1/4],...
%                         'Value',import.decay);

setup.inc = uicontrol("Style","togglebutton",...
                      "String","Waste Incinerated",...
                      "Units","inches",...
                      "Position",[30/8,15/4,4/4,1/4],...
                      "Value",import.inc);

setup.q8 = uicontrol('style','text',...
                     'string','KW Total',...
                     'units','inches',...
                     'Position',[30/8,27/8,1/2,1/4]);

setup.kwinc = uicontrol('style','edit',...
                        'string',import.kwinc,...
                        'units','inches',...
                        'position',[69/16,55/16,3/8,1/4]);

setup.moxie = uicontrol("Style","togglebutton",...
                        "String","MOXIE In Use",...
                        "Units","inches",...
                        "Position",[30/8,12/4,4/4,1/4],...
                        "Value",import.moxie);

setup.q9 = uicontrol('style','text',...
                     'string','KW Total',...
                     'units','inches',...
                     'Position',[30/8,21/8,1/2,1/4]);

setup.kwmoxie = uicontrol('style','edit',...
                          'string',import.kwmoxie,...
                          'units','inches',...
                          'position',[69/16,43/16,3/8,1/4]);

setup.assume = uicontrol('Style','checkbox',...
                         'String','Assume excess KW for all processes',...
                         'units','inches',...
                         'Position',[1/4,49/16,8/4,1/4],...
                         'Value',import.assume);

setup.q10 = uicontrol('Style','text',...
                      'String',"Leak rate",...
                      'Units','inches',...
                      'Position',[8/16,55/16,1/2,3/16]);

setup.leak = uicontrol('Style','edit',...
                       'String',import.leak,...
                       'Units','inches',...
                       'Position',[18/16,55/16,1/2,1/4]);

setup.ls = uicontrol('Style','text',...
                     'String','mL/s',...
                     'Units','inches',...
                     'Position',[26/16,55/16,1/4,3/16]);

setup.loxgox = uicontrol('Style','togglebutton',...
                         'String','LOX > GOX Converter In Use',...
                         'Units','inches',...
                         'Position',[3/8,43/16,13/8,1/4],...
                         'Value',import.loxgox);

setup.q11 = uicontrol('Style','text',...
                      'String','KW Total',...
                      'Units','inches',...
                      'Position',[5/8,36/16,1/2,1/4]);

setup.kwloxgox = uicontrol('Style','edit',...
                           'String',import.kwloxgox,...
                           'Units','inches',...
                           'Position',[20/16,37/16,1/2,1/4]);

setup.trippanel = uipanel("title","Trip",...
                          "titleposition",'centertop',...
                          'units','inches',...
                          'position',[39/8,1/16,10/4,16/16]);

setup.q12 = uicontrol('Style','text',...
                      'String',"Plan trip for given:",...
                      'Units','inches',...
                      'Position',[88/16,9/16,1/2,5/16]);

setup.triptype = uicontrol("Style","popupmenu",...
                           "String",["Trip Time","Volume"],...
                           'Units','inches',...
                           'Position',[97/16,10/16,6/8,3/16],...
                           'Value',import.triptype);

setup.q13 = uicontrol('Style','text',...
                      'String','Length, in days',...
                      'Units','inches',...
                      'Position',[80/16,2/16,8/16,5/16]);

setup.triptime = uicontrol('Style','edit',...
                           'String',import.triptime,...
                           'Units','inches',...
                           'Position',[88/16,6/32,9/16,3/16]);

setup.q14 = uicontrol('Style','text',...
                      'String','Volume, in liters',...
                      'Units','inches',...
                      'Position',[98/16,2/16,8/16,5/16]);

setup.tripvol = uicontrol('Style','edit',...
                          'String',import.tripvol,...
                          'Units','inches',...
                          'Position',[106/16,6/32,9/16,3/16]);

setup.accept = uicontrol('Style','pushbutton',...
                         'String','Accept',...
                         'Units','inches',...
                         'Position',[119/16,1/16,1/2,1/4],...
                         'Callback',@close_call);

uiwait(setup.f)

%% Input Recording

% Once the button is clicked, all of the inputs are loaded to the
% "input" and "import" variables. A few common-sense warning messages are
% provided if the user has either planned a mission that exceeds the rating
% of their 2-day LiOH scrubber or is running processes that compete for
% resources, like greenhouses with water recycling.

inputs.kerbal_num = str2double(get(setup.kerbal_num,'string'));
import.kerbal_num = get(setup.kerbal_num,'string');
if isnan(inputs.kerbal_num); inputs.kerbal_num = 0; end
inputs.scrub = get(setup.scrub,'value');
import.scrub = inputs.scrub;
inputs.press = get(setup.press,'value');
import.press = inputs.press;
inputs.rec = get(setup.rec,'value');
import.rec = inputs.rec;
inputs.kwrec = str2double(get(setup.kwrec,'string'));
import.kwrec = get(setup.kwrec,'string');
if isnan(inputs.kwrec); inputs.kwrec = 0; end
inputs.showers = str2double(get(setup.showers,'string'));
import.showers = get(setup.showers,'string');
if isnan(inputs.showers); inputs.showers = 0; end
inputs.green = get(setup.green,'value');
import.green = inputs.green;
inputs.kwgreen = str2double(get(setup.kwgreen,'string'));
import.kwgreen = get(setup.kwgreen,'string');
if isnan(inputs.kwgreen); inputs.kwgreen = 0; end
inputs.inc = get(setup.inc,'value');
import.inc = inputs.inc;
inputs.kwinc = str2double(get(setup.kwinc,'string'));
import.kwinc = get(setup.kwinc,'string');
if isnan(inputs.kwinc); inputs.kwinc = 0; end
inputs.moxie = get(setup.moxie,'value');
import.moxie = inputs.moxie;
inputs.kwmoxie = str2double(get(setup.kwmoxie,'string'));
import.kwmoxie = get(setup.kwmoxie,'string');
if isnan(inputs.kwmoxie); inputs.kwmoxie = 0; end
inputs.elec = get(setup.elec,'value');
import.elec = inputs.elec;
inputs.shadow = str2double(get(setup.shadow,'string'));
import.shadow = get(setup.shadow,'string');
if isnan(inputs.shadow); inputs.shadow = 0; end
inputs.exposure = str2double(get(setup.exposure,'string'));
import.exposure = get(setup.exposure,'string');
if isnan(inputs.exposure); inputs.exposure = 0; end
inputs.solar = str2double(get(setup.solar,'string'));
import.solar = get(setup.solar,'string');
if isnan(inputs.solar); inputs.solar = 0; end
inputs.rtg = str2double(get(setup.rtg,'string'));
import.rtg = get(setup.rtg,'string');
if isnan(inputs.rtg); inputs.rtg = 0; end
inputs.nuclear = str2double(get(setup.nuclear,'string'));
import.nuclear = get(setup.nuclear,'string');
if isnan(inputs.nuclear); inputs.nuclear = 0; end
inputs.kw = str2double(get(setup.kw,'string'));
import.kw = get(setup.kw,'string');
if isnan(inputs.kw); inputs.kw = 0; end
inputs.gemini = str2double(get(setup.gemini,'string'));
import.gemini = get(setup.gemini,'string');
if isnan(inputs.gemini); inputs.gemini = 0; end
inputs.apollo = str2double(get(setup.apollo,'string'));
import.apollo = get(setup.apollo,'string');
if isnan(inputs.apollo); inputs.apollo = 0; end
inputs.aes = str2double(get(setup.aes,'string'));
import.aes = get(setup.aes,'string');
if isnan(inputs.aes); inputs.aes = 0; end
inputs.soyuz = str2double(get(setup.soyuz,'string'));
import.soyuz = get(setup.soyuz,'string');
if isnan(inputs.soyuz); inputs.soyuz = 0; end
inputs.shuttle = str2double(get(setup.shuttle,'string'));
import.shuttle = get(setup.shuttle,'string');
if isnan(inputs.shuttle); inputs.shuttle = 0; end
inputs.ch4 = str2double(get(setup.ch4,'string'));
import.ch4 = get(setup.ch4,'string');
if isnan(inputs.ch4); inputs.ch4 = 0; end
inputs.transtime = str2double(get(setup.transtime,'string'));
import.transtime = get(setup.transtime,'string');
if isnan(inputs.transtime); inputs.transtime = 0; end
% inputs.decay = get(setup.decay,'value');
% import.decay = inputs.decay;
inputs.assume = get(setup.assume,'value');
import.assume = inputs.assume;
inputs.leak = str2double(get(setup.leak,'string')) / 1000;
import.leak = get(setup.leak,'string');
if isnan(inputs.leak); inputs.leak = 0; end
inputs.loxgox = get(setup.loxgox,'value');
import.loxgox = inputs.loxgox;
inputs.kwloxgox = str2double(get(setup.kwloxgox,'string'));
inputs.kwloxgox = get(setup.kwloxgox,'string');
if isnan(inputs.kwloxgox); inputs.kwloxgox = 0; end
inputs.triptype = get(setup.triptype,'value');
import.triptype = inputs.triptype;
inputs.triptime = str2double(get(setup.triptime,'string'));
import.triptime = get(setup.triptime,'string');
if isnan(inputs.triptime); inputs.triptime = 0; end
inputs.tripvol = str2double(get(setup.tripvol,'string'));
import.tripvol = get(setup.tripvol,'string');
if isnan(inputs.tripvol); inputs.tripvol = 0; end

close(setup.f)

if inputs.rec == 1 && inputs.green == 1
    warn.rec = warndlg(["Waste water is the rate limiting input to a greenhouse."; ...
                        "Use of both water recyclers and a greenhouse is not advised."]);
    uiwait(warn.rec)
end

if (inputs.green || inputs.moxie) && not(inputs.scrub == 1 || inputs.scrub == 2 || inputs.ch4 ~= 0)
    warn.green = warndlg(["CO2 consuming components used, but CO2 is not produced!"; ...
                          "Use vacuum scrubbers to produce CO2"]);
    uiwait(warn.green)
end

if inputs.assume == 1
    inputs.kwrec = (inputs.rec == 1) * 1E12;
    inputs.kwgreen = (inputs.green == 1) * 1E12;
    inputs.kwmoxie = (inputs.moxie == 1) * 1E12;
    inputs.kwinc = (inputs.inc == 1) * 1E12;
    inputs.kwloxgox = (inputs.loxgox == 1) * 1E12;
end

%% Gaseus and Battery Volume Multipliers

% Hydgrogen, Oxygen, and Nitrogen are compressed and occupy less volume
% than their uncompressed forms which are used for kerbals and processes.
% For batteries, 1 liter holds 1000 KW.

% These will be multipied against uncompressed units that real tanks
% expects the user to type in to find the real volume, and divided from the
% real volume to find the uncompressed units the user should enter into
% real fuels.

vmult.oxygen = 0.005;
vmult.nitrogen = 0.005;
vmult.hydrogen = 0.01;
vmult.batt = 0.001;
vmult.CO2 = 0.005;

%% Battery Rates

% This section calculates the per second usage of the battery, as averaged
% over time. 

if inputs.elec == 1
    res.KWBalance.stable = inputs.kw...
                      -inputs.solar * inputs.shadow * inputs.exposure...
                      -inputs.rtg...
                      -inputs.nuclear...
                      -inputs.gemini...
                      -inputs.apollo...
                      -inputs.aes...
                      -inputs.soyuz...
                      -inputs.shuttle...
                      -inputs.ch4;

    if res.KWBalance.stable > 0
        res.batt.stable = res.KWBalance / 1000;
    else
        res.batt.stable = 0;
    end

    res.KWBalance.transfer = inputs.kw...
                      -inputs.solar * inputs.exposure...
                      -inputs.rtg...
                      -inputs.nuclear...
                      -inputs.gemini...
                      -inputs.apollo...
                      -inputs.aes...
                      -inputs.soyuz...
                      -inputs.shuttle...
                      -inputs.ch4;

    if res.KWBalance.transfer > 0
        res.batt.transfer = res.KWBalance / 1000;
    else
        res.batt.transfer = 0;
    end

%% Fuel Cell Rates

% this code assumes all fuel cells operate at their max electrical load
% required, and that excess products are dumped. This is assumed to avoid
% circular logic that is beyond my coding capabilities.

% this section calculates kilowatts that fuel cells must provide, splits
% their loads in accordance with their kw value, then determines resources
% rates for the interplanetary transfer phase of flight and the stable
% orbiting or landed phase of flight.

    if inputs.nuclear ~= 0
        warn.nuclear = warndlg(["This code assumes the selected reactor"; ...
                                "is rated to operate for mission duration"; ...
                                "and comes with sufficient fuel"]);
        uiwait(warn.nuclear)
    end
    res.KWDemand = inputs.kw...
                   -inputs.solar * inputs.shadow * inputs.exposure...
                   -inputs.rtg...
                   -inputs.nuclear;
    if res.KWDemand < 0; res.KWDemand = 0; end
    res.KWTransfer = inputs.kw * inputs.exposure...
                    -inputs.solar...
                    -inputs.rtg...
                    -inputs.nuclear;
    if res.KWTransfer < 0; res.KWTransfer = 0; end
    res.fctotal = inputs.gemini...
                 +inputs.apollo...
                 +inputs.aes...
                 +inputs.soyuz...
                 +inputs.shuttle...
                 +inputs.ch4;

    if res.fctotal > 0
        res.prop.gemini = inputs.gemini/res.fctotal;
        res.prop.apollo = inputs.apollo/res.fctotal;
        res.prop.aes = inputs.aes/res.fctotal;
        res.prop.soyuz = inputs.soyuz/res.fctotal;
        res.prop.shuttle = inputs.shuttle/res.fctotal;
        res.prop.ch4 = inputs.ch4/res.fctotal;
    else                                  % this section prevents NaN when no fuel cells are used
        res.prop.gemini = 0;
        res.prop.apollo = 0;
        res.prop.aes = 0;
        res.prop.soyuz = 0;
        res.prop.shuttle = 0;
        res.prop.ch4 = 0;
    end

    res.fc.gemini.lox.stable = res.KWDemand * res.prop.gemini * rate.fc.gem.lox;
    res.fc.gemini.lh2.stable = res.KWDemand * res.prop.gemini * rate.fc.gem.lh2;
    res.fc.gemini.water.stable = res.KWDemand * res.prop.gemini * rate.fc.gem.water;
    res.fc.apollo.lox.stable = res.KWDemand * res.prop.apollo * rate.fc.apollo.lox;
    res.fc.apollo.lh2.stable = res.KWDemand * res.prop.apollo * rate.fc.apollo.lh2;
    res.fc.apollo.water.stable = res.KWDemand * res.prop.apollo * rate.fc.apollo.water;
    res.fc.aes.O2.stable = res.KWDemand * res.prop.aes * rate.fc.aes.O2;
    res.fc.aes.H2.stable = res.KWDemand * res.prop.aes * rate.fc.aes.H2;
    res.fc.aes.water.stable = res.KWDemand * res.prop.aes * rate.fc.aes.water;
    res.fc.soyuz.lox.stable = res.KWDemand * res.prop.soyuz * rate.fc.soyuz.lox;
    res.fc.soyuz.lh2.stable = res.KWDemand * res.prop.soyuz * rate.fc.soyuz.lh2;
    res.fc.soyuz.water.stable = res.KWDemand * res.prop.soyuz * rate.fc.soyuz.water;
    res.fc.shuttle.lox.stable = res.KWDemand * res.prop.shuttle * rate.fc.shuttle.lox;
    res.fc.shuttle.lh2.stable = res.KWDemand * res.prop.shuttle * rate.fc.shuttle.lh2;
    res.fc.shuttle.water.stable = res.KWDemand * res.prop.shuttle * rate.fc.shuttle.water;
    res.fc.ch4.lox.stable = res.KWDemand * res.prop.ch4 * rate.fc.ch4.lox;
    res.fc.ch4.liqmeth.stable = res.KWDemand * res.prop.ch4 * rate.fc.ch4.liqmeth;
    res.fc.ch4.water.stable = res.KWDemand * res.prop.ch4 * rate.fc.ch4.water;
    res.fc.ch4.CO2.stable = res.KWDemand * res.prop.ch4 * rate.fc.ch4.CO2;

    res.fc.gemini.lox.transfer = res.KWTransfer * res.prop.gemini * rate.fc.gem.lox;
    res.fc.gemini.lh2.transfer = res.KWTransfer * res.prop.gemini * rate.fc.gem.lh2;
    res.fc.gemini.water.transfer = res.KWTransfer * res.prop.gemini * rate.fc.gem.water;
    res.fc.apollo.lox.transfer = res.KWTransfer * res.prop.apollo * rate.fc.apollo.lox;
    res.fc.apollo.lh2.transfer = res.KWTransfer * res.prop.apollo * rate.fc.apollo.lh2;
    res.fc.apollo.water.transfer = res.KWTransfer * res.prop.apollo * rate.fc.apollo.water;
    res.fc.aes.O2.transfer = res.KWTransfer * res.prop.aes * rate.fc.aes.O2;
    res.fc.aes.H2.transfer = res.KWTransfer * res.prop.aes * rate.fc.aes.H2;
    res.fc.aes.water.transfer = res.KWTransfer * res.prop.aes * rate.fc.aes.water;
    res.fc.soyuz.lox.transfer = res.KWTransfer * res.prop.soyuz * rate.fc.soyuz.lox;
    res.fc.soyuz.lh2.transfer = res.KWTransfer * res.prop.soyuz * rate.fc.soyuz.lh2;
    res.fc.soyuz.water.transfer = res.KWTransfer * res.prop.soyuz * rate.fc.soyuz.water;
    res.fc.shuttle.lox.transfer = res.KWTransfer * res.prop.shuttle * rate.fc.shuttle.lox;
    res.fc.shuttle.lh2.transfer = res.KWTransfer * res.prop.shuttle * rate.fc.shuttle.lh2;
    res.fc.shuttle.water.transfer = res.KWTransfer * res.prop.shuttle * rate.fc.shuttle.water;
    res.fc.ch4.lox.transfer = res.KWTransfer * res.prop.ch4 * rate.fc.ch4.lox;
    res.fc.ch4.liqmeth.transfer = res.KWTransfer * res.prop.ch4 * rate.fc.ch4.liqmeth;
    res.fc.ch4.water.transfer = res.KWTransfer * res.prop.ch4 * rate.fc.ch4.water;
    res.fc.ch4.CO2.transfer = res.KWTransfer * res.prop.ch4 * rate.fc.ch4.CO2;

else

    res.batt.stable = 0;
    res.fc.gemini.lox.stable = 0;
    res.fc.gemini.lh2.stable = 0;
    res.fc.gemini.water.stable = 0;
    res.fc.apollo.lox.stable = 0;
    res.fc.apollo.lh2.stable = 0;
    res.fc.apollo.water.stable = 0;
    res.fc.aes.O2.stable = 0;
    res.fc.aes.H2.stable = 0;
    res.fc.aes.water.stable = 0;
    res.fc.soyuz.lox.stable = 0;
    res.fc.soyuz.lh2.stable = 0;
    res.fc.soyuz.water.stable = 0;
    res.fc.shuttle.lox.stable = 0;
    res.fc.shuttle.lh2.stable = 0;
    res.fc.shuttle.water.stable = 0;
    res.fc.ch4.lox.stable = 0;
    res.fc.ch4.liqmeth.stable = 0;
    res.fc.ch4.water.stable = 0;
    res.fc.ch4.CO2.stable = 0;

    res.batt.transfer = 0;
    res.fc.gemini.lox.transfer = 0;
    res.fc.gemini.lh2.transfer = 0;
    res.fc.gemini.water.transfer = 0;
    res.fc.apollo.lox.transfer = 0;
    res.fc.apollo.lh2.transfer = 0;
    res.fc.apollo.water.transfer = 0;
    res.fc.aes.O2.transfer = 0;
    res.fc.aes.H2.transfer = 0;
    res.fc.aes.water.transfer = 0;
    res.fc.soyuz.lox.transfer = 0;
    res.fc.soyuz.lh2.transfer = 0;
    res.fc.soyuz.water.transfer = 0;
    res.fc.shuttle.lox.transfer = 0;
    res.fc.shuttle.lh2.transfer = 0;
    res.fc.shuttle.water.transfer = 0;
    res.fc.ch4.lox.transfer = 0;
    res.fc.ch4.liqmeth.transfer = 0;
    res.fc.ch4.water.transfer = 0;
    res.fc.ch4.CO2.transfer = 0;

end

%% Nitrogen, Scrubber, Waste, and Waste Atmosphere Rates

res.nitrogen = (inputs.press == 1) * inputs.leak;
res.wasteatm = inputs.kerbal_num * pk.wasteatm;
res.lioh = (inputs.scrub == 4) * res.wasteatm / rate.scrub.lion.wasteatm * rate.scrub.lion.LiH2...
          +(inputs.scrub == 5) * res.wasteatm / rate.scrub.lion2.wasteatm * rate.scrub.lion2.LiH2;
res.KO3 = (inputs.scrub == 3) * res.wasteatm / rate.scrub.pot.wasteatm * rate.scrub.pot.KO3;

if (inputs.kwinc * rate.proc.inc.waste) > ( ...
                                            inputs.kerbal_num * pk.waste...
                                          +(inputs.scrub == 4) * res.wasteatm / rate.scrub.lion.wasteatm * rate.scrub.lion.waste...
                                          +(inputs.scrub == 5) * res.wasteatm / rate.scrub.lion2.wasteatm * rate.scrub.lion2.waste...
                                          +(inputs.scrub == 3) * res.wasteatm / rate.scrub.pot.wasteatm * rate.scrub.pot.waste...
                                          )
    res.kwinc = (inputs.kerbal_num * pk.waste...
                 +(inputs.scrub == 4) * res.wasteatm / rate.scrub.lion.wasteatm * rate.scrub.lion.waste...
                 +(inputs.scrub == 5) * res.wasteatm / rate.scrub.lion2.wasteatm * rate.scrub.lion2.waste...
                 +(inputs.scrub == 3) * res.wasteatm / rate.scrub.pot.wasteatm * rate.scrub.pot.waste)...
                 /rate.proc.inc.waste;
    res.waste = 0;
else
    res.kwinc = inputs.kwinc;
    res.waste = inputs.kerbal_num * pk.waste...
               +(inputs.scrub == 4) * res.wasteatm / rate.scrub.lion.wasteatm * rate.scrub.lion.waste...
               +(inputs.scrub == 5) * res.wasteatm / rate.scrub.lion2.wasteatm * rate.scrub.lion2.waste...
               +(inputs.scrub == 3) * res.wasteatm / rate.scrub.pot.wasteatm * rate.scrub.pot.waste...
               -inputs.kwinc * rate.proc.inc.waste;
end

%% Food, Water, and Wastewater Rates

if inputs.green == 0

    if (inputs.kwrec * rate.proc.rec.wastewater) > ( ...
                                                     inputs.kerbal_num * pk.wastewater ...
                                                    +inputs.showers * rate.comfort.shower.wastewater...
                                                    )
        inputs.kwrec = ( ...
                         inputs.kerbal_num * pk.wastewater ...
                        +inputs.showers * rate.comfort.shower.wastewater ...
                        ) ...
                        / rate.proc.rec.wastewater;
        res.wastewater.stable = 0;
        res.wastewater.transfer = 0;
    end

    res.wastewater.stable = inputs.kerbal_num * pk.wastewater...
                           -inputs.kwrec * rate.proc.rec.wastewater...
                           +inputs.showers * rate.comfort.shower.wastewater;
    res.wastewater.transfer = res.wastewater.stable;

    res.water.stable = inputs.kerbal_num * pk.water...
                      -inputs.kwrec * rate.proc.rec.water...
                      -res.fc.gemini.water.stable...
                      -res.fc.apollo.water.stable...
                      -res.fc.aes.water.stable...
                      -res.fc.soyuz.water.stable...
                      -res.fc.shuttle.water.stable...
                      -res.fc.ch4.water.stable...
                      -res.kwinc * rate.proc.inc.water...
                      +inputs.showers * rate.comfort.shower.water;
    if res.water.stable < 0
        res.water.stable = 0;
        warn.water = warndlg("Excess water produced, dumping assumed");
        warn.flag = 1;
        uiwait(warn.water);
    else
        warn.flag = 0;
    end

    res.water.transfer = inputs.kerbal_num * pk.water...
                        -inputs.kwrec * rate.proc.rec.water...
                        -res.fc.gemini.water.transfer...
                        -res.fc.apollo.water.transfer...
                        -res.fc.aes.water.transfer...
                        -res.fc.soyuz.water.transfer...
                        -res.fc.shuttle.water.transfer...
                        -res.fc.ch4.water.transfer...
                        -res.kwinc * rate.proc.inc.water...
                        +inputs.showers * rate.comfort.shower.water;
    if res.water.transfer < 0 && not(warn.flag)
        res.water.transfer = 0;
        warn.water = warndlg("Excess water produced, dumping assumed");
        uiwait(warn.water);
    end
    
    if (inputs.kwmoxie * rate.proc.moxie.CO2) > ( ...
                                                  (inputs.scrub == 1) * res.wasteatm * rate.scrub.adv.CO2 / rate.scrub.adv.wasteatm...
                                                 +(inputs.scrub == 2) * res.wasteatm * rate.scrub.vac.CO2 / rate.scrub.vac.wasteatm...
                                                 +res.fc.ch4.CO2.stable...
                                                 )
        res.kwmoxie.stable = ( ...
                              (inputs.scrub == 1) * res.wasteatm * rate.scrub.adv.CO2 / rate.scrub.adv.wasteatm...
                             +(inputs.scrub == 2) * res.wasteatm * rate.scrub.vac.CO2 / rate.scrub.vac.wasteatm...
                             +res.fc.ch4.CO2.stable...
                             +res.kwinc * rate.proc.inc.CO2 ...
                             )...
                             /rate.proc.moxie.CO2;
    else
        res.kwmoxie.stable = inputs.kwmoxie;
    end

    if (inputs.kwmoxie * rate.proc.moxie.CO2) > ( ...
                                                  (inputs.scrub == 1) * res.wasteatm * rate.scrub.adv.CO2 / rate.scrub.adv.wasteatm...
                                                 +(inputs.scrub == 2) * res.wasteatm * rate.scrub.vac.CO2 / rate.scrub.vac.wasteatm...
                                                 +res.fc.ch4.CO2.transfer...
                                                 )
        res.kwmoxie.transfer = ( ...
                                (inputs.scrub == 1) * res.wasteatm * rate.scrub.adv.CO2 / rate.scrub.adv.wasteatm...
                               +(inputs.scrub == 2) * res.wasteatm * rate.scrub.vac.CO2 / rate.scrub.vac.wasteatm...
                               +res.fc.ch4.CO2.transfer ...
                               )...
                               /rate.proc.moxie.CO2;
    else
        res.kwmoxie.transfer = inputs.kwmoxie;
    end

    res.kwgreen.stable = 0;
    res.kwgreen.transfer = 0;

elseif inputs.green == 1 && inputs.rec == 0 && inputs.moxie == 0

    res.kwmoxie.stable = 0;
    res.kwmoxie.transfer = 0;

    if inputs.kwgreen * rate.proc.bioreactor.wastewater > (inputs.kerbal_num * pk.wastewater + inputs.showers * rate.comfort.shower.wastewater)
        res.kwgreen.stable = (inputs.kerbal_num * pk.wastewater + inputs.showers * rate.comfort.shower.wastewater) / rate.proc.bioreactor.wastewater;
        res.kwgreen.transfer = (inputs.kerbal_num * pk.wastewater + inputs.showers * rate.comfort.shower.wastewater) / rate.proc.bioreactor.wastewater;
    end

    if res.kwgreen.stable * rate.proc.bioreactor.CO2 > (...
                                                         (inputs.scrub == 1) * res.wasteatm * rate.scrub.adv.CO2 / rate.scrub.adv.wasteatm...
                                                        +(inputs.scrub == 2) * res.wasteatm * rate.scrub.vac.CO2 / rate.scrub.vac.wasteatm...
                                                        +res.fc.ch4.CO2.stable...
                                                        +res.kwinc * rate.proc.inc.CO2...
                                                        )
        res.kwgreen.stable = ( ...
                              (inputs.scrub == 1) * res.wasteatm * rate.scrub.adv.CO2 / rate.scrub.adv.wasteatm...
                             +(inputs.scrub == 2) * res.wasteatm * rate.scrub.vac.CO2 / rate.scrub.vac.wasteatm...
                             +res.fc.ch4.CO2.stable...
                             +res.kwinc * rate.proc.inc.CO2 ...
                             )...
                             /rate.proc.bioreactor.CO2;
    end

    if res.kwgreen.transfer * rate.proc.bioreactor.CO2 > (...
                                                           (inputs.scrub == 1) * res.wasteatm * rate.scrub.adv.CO2 / rate.scrub.adv.wasteatm...
                                                          +(inputs.scrub == 2) * res.wasteatm * rate.scrub.vac.CO2 / rate.scrub.vac.wasteatm...
                                                          +res.fc.ch4.CO2.transfer...
                                                          +res.kwinc * rate.proc.inc.CO2...
                                                          )
        res.kwgreen.transfer = ( ...
                                (inputs.scrub == 1) * res.wasteatm * rate.scrub.adv.CO2 / rate.scrub.adv.wasteatm...
                               +(inputs.scrub == 2) * res.wasteatm * rate.scrub.vac.CO2 / rate.scrub.vac.wasteatm...
                               +res.fc.ch4.CO2.transfer...
                               +res.kwinc * rate.proc.inc.CO2...
                               ) ...
                               /rate.proc.bioreactor.CO2;
    end

    res.water.stable = inputs.kerbal_num * pk.water...
                      -res.kwgreen.stable * rate.proc.bioreactor.water...
                      -res.fc.gemini.water.stable...
                      -res.fc.apollo.water.stable...
                      -res.fc.aes.water.stable...
                      -res.fc.soyuz.water.stable...
                      -res.fc.shuttle.water.stable...
                      -res.fc.ch4.water.stable...
                      -res.kwinc * rate.proc.inc.water...
                      +inputs.showers * rate.comfort.shower.wastewater;
    if res.water.stable < 0
        res.water.stable = 0;
        warn.water = warndlg("Excess water produced, dumping assumed");
        warn.flag = 1;
        uiwait(warn.water);
    else
        warn.flag = 0;
    end

    res.water.transfer = inputs.kerbal_num * pk.water...
                      -res.kwgreen.transfer * rate.proc.bioreactor.water...
                      -res.fc.gemini.water.transfer...
                      -res.fc.apollo.water.transfer...
                      -res.fc.aes.water.transfer...
                      -res.fc.soyuz.water.transfer...
                      -res.fc.shuttle.water.transfer...
                      -res.fc.ch4.water.transfer...
                      -res.kwinc * rate.proc.inc.water...
                      +inputs.showers * rate.comfort.shower.wastewater;
    if res.water.transfer < 0 && not(warn.flag)
        res.water.transfer = 0;
        warn.water = warndlg("Excess water produced, dumping assumed");
        uiwait(warn.water);
    end

    res.wastewater.stable = inputs.kerbal_num * pk.wastewater - res.kwgreen.stable * rate.proc.bioreactor.wastewater;
    res.wastewater.transfer = inputs.kerbal_num * pk.wastewater - res.kwgreen.transfer * rate.proc.bioreactor.wastewater;
else
    warn.simul = warndlg(["Simultaneous use of greenhouse and"; ...
                          "either a water recycler or MOXIE"; ...
                          "is not supported currently"]);
    uiwait(warn.simul)
    % Write system to deal with simultaneous greenhouse and moxie and/or
    % recycler
end

res.food.stable = inputs.kerbal_num * pk.food - res.kwgreen.stable * rate.proc.bioreactor.food;

if res.food.stable < 0
    res.food.stable = 0;
    warn.food = warndlg("Excess food produced, dumping assumed");
    uiwait(warn.food)
end

res.food.transfer = inputs.kerbal_num * pk.food - res.kwgreen.transfer * rate.proc.bioreactor.food;

if res.food.transfer < 0
    res.food.transfer = 0;
end

%% LOX, LH2, H2 and Liquid Methane Rates

if (inputs.kwloxgox * rate.proc.lox.O2) > ( ...
                                            inputs.kerbal_num * pk.oxygen...
                                           +(inputs.press == 2) * inputs.leak ...
                                           +res.kwinc * rate.proc.inc.O2 ...
                                           +res.fc.aes.O2.stable ...
                                           -(inputs.scrub == 3) * res.wasteatm / rate.scrub.pot.wasteatm * rate.scrub.pot.O2...
                                           -res.kwgreen.stable * rate.proc.bioreactor.O2...
                                           -res.kwmoxie.stable * rate.proc.moxie.O2...
                                           )
    if ( ...
         inputs.kerbal_num * pk.oxygen...
       +(inputs.press == 2) * inputs.leak ...
       +res.kwinc * rate.proc.inc.O2 ...
       +res.fc.aes.O2.stable ...
       -(inputs.scrub == 3) * res.wasteatm / rate.scrub.pot.wasteatm * rate.scrub.pot.O2 ...
       -res.kwgreen.stable * rate.proc.bioreactor.O2 ...
       -res.kwmoxie.stable * rate.proc.moxie.O2 ...
       ) > 0
        res.kwloxgox.stable = ( ...
                               inputs.kerbal_num * pk.oxygen ...
                              +(inputs.press == 2) * inputs.leak ...
                              +res.kwinc * rate.proc.inc.O2 ...
                              +res.fc.aes.O2.stable ...
                              -(inputs.scrub == 3) * res.wasteatm / rate.scrub.pot.wasteatm * rate.scrub.pot.O2 ...
                              -res.kwgreen.stable * rate.proc.bioreactor.O2 ...
                              -res.kwmoxie.stable * rate.proc.moxie.O2 ...;
                              ) ... 
                              /rate.proc.lox.O2;
    else
        res.kwloxgox.stable = 0;
    end
else
    res.kwloxgox.stable = 0;
end

if (inputs.kwloxgox * rate.proc.lox.O2) > (...
                                            inputs.kerbal_num * pk.oxygen + (inputs.press == 2) * inputs.leak ...
                                           +(inputs.press == 2) * inputs.leak ...
                                           +res.kwinc * rate.proc.inc.O2 ...
                                           +res.fc.aes.O2.transfer ...
                                           -(inputs.scrub == 3) * res.wasteatm / rate.scrub.pot.wasteatm * rate.scrub.pot.O2 ...
                                           -res.kwgreen.transfer * rate.proc.bioreactor.O2 ...
                                           -res.kwmoxie.transfer * rate.proc.moxie.O2 ...
                                           )
    if (inputs.kerbal_num * pk.oxygen ...
      +(inputs.press == 2) * inputs.leak ...
      +res.kwinc * rate.proc.inc.O2 ...
      +res.fc.aes.O2.transfer ...
      -(inputs.scrub == 3) * res.wasteatm / rate.scrub.pot.wasteatm * rate.scrub.pot.O2 ...
      -res.kwgreen.transfer * rate.proc.bioreactor.O2 ...
      -res.kwmoxie.transfer * rate.proc.moxie.O2 ...
      ) > 0
        res.kwloxgox.transfer = ( ...
                                 inputs.kerbal_num * pk.oxygen ...
                                +(inputs.press == 2) * inputs.leak ...
                                +res.kwinc * rate.proc.inc.O2 ...
                                +res.fc.aes.O2.transfer...
                                -(inputs.scrub == 3) * res.wasteatm / rate.scrub.pot.wasteatm * rate.scrub.pot.O2 ...
                                -res.kwgreen.transfer * rate.proc.bioreactor.O2 ...
                                -res.kwmoxie.transfer * rate.proc.moxie.O2 ...
                                )...
                                /rate.proc.lox.O2;
    else
        res.kwloxgox.transfer = 0;
    end
else
    res.kwloxgox.transfer = 0;
end

res.lox.stable = res.kwloxgox.stable * rate.proc.lox.lox...
                +res.fc.gemini.lox.stable...
                +res.fc.apollo.lox.stable...
                +res.fc.soyuz.lox.stable...
                +res.fc.shuttle.lox.stable...
                +res.fc.ch4.lox.stable;
res.lox.transfer = res.kwloxgox.transfer * rate.proc.lox.lox...
                  +res.fc.gemini.lox.transfer...
                  +res.fc.apollo.lox.transfer...
                  +res.fc.soyuz.lox.transfer...
                  +res.fc.shuttle.lox.transfer...
                  +res.fc.ch4.lox.transfer;

res.lh2.stable = res.fc.gemini.lh2.stable...
                +res.fc.apollo.lh2.stable...
                +res.fc.soyuz.lh2.stable...
                +res.fc.shuttle.lh2.stable;

res.lh2.transfer = res.fc.gemini.lh2.transfer...
                  +res.fc.apollo.lh2.transfer...
                  +res.fc.soyuz.lh2.transfer...
                  +res.fc.shuttle.lh2.stable;

res.hydrogen.stable = res.fc.aes.H2.stable;
res.hydrogen.transfer = res.fc.aes.H2.transfer;

res.liqmeth.stable = res.fc.ch4.liqmeth.stable;
res.liqmeth.transfer = res.fc.ch4.liqmeth.transfer;

%% Oxygen Rate

res.oxygen.stable = inputs.kerbal_num * pk.oxygen...
                  +(inputs.press == 2) * inputs.leak ...
                  +res.kwinc * rate.proc.inc.O2...
                  +res.fc.aes.O2.stable...
                  -(inputs.scrub == 3) * res.wasteatm / rate.scrub.pot.wasteatm * rate.scrub.pot.O2...
                  -res.kwgreen.stable * rate.proc.bioreactor.O2...
                  -res.kwloxgox.stable * rate.proc.lox.O2...
                  -res.kwmoxie.stable * rate.proc.moxie.O2;
if res.oxygen.stable < 0
    res.oxygen.stable = 0;
end

res.oxygen.transfer = inputs.kerbal_num * pk.oxygen...
                  +(inputs.press == 2) * inputs.leak ...
                  +res.kwinc * rate.proc.inc.O2...
                  +res.fc.aes.O2.stable...
                  -(inputs.scrub == 3) * res.wasteatm / rate.scrub.pot.wasteatm * rate.scrub.pot.O2...
                  -res.kwgreen.transfer * rate.proc.bioreactor.O2...
                  -res.kwloxgox.transfer * rate.proc.lox.O2...
                  -res.kwmoxie.transfer * rate.proc.moxie.O2;
if res.oxygen.transfer < 0
    res.oxygen.transfer = 0;
end

%% Volume and Time Calculations

volume.PerSecond.stable = res.food.stable...
                         +res.water.stable...
                         +res.oxygen.stable * vmult.oxygen...
                         +res.nitrogen * vmult.nitrogen...
                         +res.KO3...
                         +res.lioh...
                         +res.lox.stable...
                         +res.lh2.stable...
                         +res.hydrogen.stable * vmult.hydrogen...
                         +res.liqmeth.stable...
                         +res.waste...
                         +res.wastewater.stable...
                         +res.batt.stable * vmult.batt;

volume.PerSecond.transfer = res.food.transfer...
                           +res.water.transfer...
                           +res.oxygen.transfer * vmult.oxygen...
                           +res.nitrogen * vmult.nitrogen...
                           +res.KO3...
                           +res.lioh...
                           +res.lox.transfer...
                           +res.lh2.transfer...
                           +res.hydrogen.transfer * vmult.hydrogen...
                           +res.liqmeth.transfer...
                           +res.waste...
                           +res.wastewater.transfer...
                           +res.batt.transfer * vmult.batt;

volume.PerDay.stable = volume.PerSecond.stable * 3600 * 24;
volume.PerDay.transfer = volume.PerSecond.transfer * 3600 * 24;

if inputs.triptype == 1
    trip.days = inputs.triptime;
    if trip.days < inputs.transtime
        warn.tripless = warndlg("Time of trip is less than time of transfer");
        res.food.stable = res.food.transfer;
        res.water.stable = res.water.transfer;
        res.oxygen.stable = res.oxygen.transfer;
        res.wastewater.stable = res.wastewater.transfer;
        res.lox.stable = res.lox.transfer;
        res.lh2.stable = res.lh2.transfer;
        res.hydrogen.stable = res.hydrogen.transfer;
        res.liqmeth.stable = res.liqmeth.transfer;
        res.batt.stable = res.batt.transfer;
    end
    trip.vol = volume.PerDay.stable * (trip.days - inputs.transtime)...
              +volume.PerDay.transfer * inputs.transtime;
    trip.stable = trip.days - inputs.transtime;
    trip.transfer = inputs.transtime;
elseif inputs.triptype == 2
    trip.vol = inputs.tripvol;
    if trip.vol < volume.PerDay.transfer * inputs.transtime
        warn.trans = warndlg("Not enough volume to complete transfer!");
        uiwait(warn.trans)
        trip.days = trip.vol/volume.PerDay.transfer;
        res.food.stable = res.food.transfer;
        res.water.stable = res.water.transfer;
        res.oxygen.stable = res.oxygen.transfer;
        res.wastewater.stable = res.wastewater.transfer;
        res.lox.stable = res.lox.transfer;
        res.lh2.stable = res.lh2.transfer;
        res.hydrogen.stable = res.hydrogen.transfer;
        res.liqmeth.stable = res.liqmeth.transfer;
        res.batt.stable = res.batt.transfer;
    else
        trip.days = inputs.transtime + (trip.vol - inputs.transtime * volume.PerDay.transfer) / volume.PerDay.stable;
    end
    trip.stable = trip.days - inputs.transtime;
    trip.transfer = inputs.transtime;
end

if inputs.scrub == 5 && trip.days > 2
    warn.lioh2day = warndlg(["Warning! Mission length";"exceeds scrubber lifetime"]);
    uiwait(warn.lioh2day)
end

%% Resource Calculations

% this section multiples the per second resource rates by 3600 seconds per
% hour and 24 hours per day to get the daily resource rates for both
% interplanetary travel and for stable orbit/landed conditions, then
% multiplies those rates by the times of transit and mission time.

volume.food = res.food.stable * trip.stable * 3600 * 24 ...
             +res.food.transfer * trip.transfer * 3600 * 24;
volume.water = res.water.stable * trip.stable * 3600 * 24 ...
              +res.water.transfer * trip.transfer * 3600 * 24;
volume.oxygen = ( ...
                res.oxygen.stable * trip.stable * 3600 * 24 ...
               +res.oxygen.transfer * trip.transfer * 3600 * 24 ...
               )...
               * vmult.oxygen;
volume.nitrogen = res.nitrogen * trip.days * 3600 * 24 ...
                 * vmult.nitrogen;
volume.lioh = res.lioh * trip.days * 3600 *24;
volume.KO3 = res.KO3 * trip.days * 3600 * 24;
volume.lox = res.lox.stable * trip.stable * 3600 * 24 ...
            +res.lox.transfer * trip.transfer * 3600 * 24;
volume.lh2 = res.lh2.stable * trip.stable * 3600 * 24 ...
            +res.lh2.transfer * trip.transfer * 3600 * 24;
volume.hydrogen = ( ...
                  res.hydrogen.stable * trip.stable * 3600 * 24 ...
                 +res.hydrogen.transfer * trip.transfer * 3600 * 24 ...
                 ) ...
                 * vmult.hydrogen;
volume.liqmeth = res.liqmeth.stable * trip.stable * 3600 * 24 ...
                +res.liqmeth.transfer * trip.transfer * 3600 * 24;
volume.batt = ( ...
               res.batt.stable * trip.stable * 3600 * 24 ...
              +res.batt.transfer * trip.transfer * 3600 * 24 ...
              ) ...
              * vmult.batt;     % 1000 KJ/Liter
volume.wastewater = res.wastewater.stable * trip.stable * 3600 * 24 ...
                   +res.wastewater.transfer * trip.transfer * 3600 * 24;
volume.waste = res.waste * trip.days * 3600 * 24;

%% Tank Spare Space

% this section creates minimum volumes for resouces like water and oxygen
% to allow processes to output to these tanks, and provide small time
% margins in case of failures. Players may want larger margins. It also
% generates small tanks for processes that consume some resources that
% would otherwise be dumped, and consume them faster than they are
% produced.

% Due to the sequential nature of this process, the ealier spares shrink
% with each subsequent spare tank

spare.water = 1/4 * pk.water * 24 * 3600;
if volume.water < (spare.water * inputs.kerbal_num)
    if inputs.triptype == 1
        trip.vol = trip.vol - volume.water;
        volume.water = (spare.water * inputs.kerbal_num);
        trip.vol = trip.vol + volume.water;
    elseif inputs.triptype == 2
        delta.water = (spare.water * inputs.kerbal_num) - volume.water;
        delta.fraction = (trip.volume - delta.water) / trip.volume;
        volume.food = volume.food * delta.fraction;
        volume.water = spare.water * inputs.kerbal_num;
        volume.oxygen = volume.oxygen * delta.fraction;
        volume.nitrogen = volume.nitrogen * delta.fraction;
        volume.lioh = volume.lioh * delta.fraction;
        volume.KO3 = volume.KO3 * delta.fraction;
        volume.lox = volume.lox * delta.fraction;
        volume.lh2 = volume.lh2 * delta.fraction;
        volume.hydrogen = volume.hydrogen * delta.fraction;
        volume.liqmeth = volume.liqmeth * delta.fraction;
        volume.batt = volume.batt * delta.fraction;
        volume.waste = volume.waste * delta.fraction;
        volume.wastewater = volume.wastewater * delta.fraction;
    end
end

spare.oxgyen = 1/4 * pk.oxygen * 24 * 3600;
if volume.oxygen < (spare.oxgyen * inputs.kerbal_num * vmult.oxygen)
    if inputs.triptype == 1
        trip.vol = trip.vol - volume.oxygen;
        volume.oxygen = (spare.oxgyen * inputs.kerbal_num * vmult.oxygen);
        trip.vol = trip.vol + volume.oxygen;
    elseif inputs.triptype == 2
        delta.oxygen = (spare.oxgyen * inputs.kerbal_num * vmult.oxygen) - volume.oxygen;
        delta.fraction = (trip.volume - delta.oxygen) / trip.volume;
        volume.food = volume.food * delta.fraction;
        volume.water = volume.water * delta.fraction;
        volume.oxygen = spare.oxgyen * inputs.kerbal_num;
        volume.nitrogen = volume.nitrogen * delta.fraction;
        volume.lioh = volume.lioh * delta.fraction;
        volume.KO3 = volume.KO3 * delta.fraction;
        volume.lox = volume.lox * delta.fraction;
        volume.lh2 = volume.lh2 * delta.fraction;
        volume.hydrogen = volume.hydrogen * delta.fraction;
        volume.liqmeth = volume.liqmeth * delta.fraction;
        volume.batt = volume.batt * delta.fraction;
        volume.waste = volume.waste * delta.fraction;
        volume.wastewater = volume.wastewater * delta.fraction;
    end
end

spare.batt = 25000;
if volume.batt < (spare.batt * inputs.kerbal_num * vmult.batt)
    if inputs.triptype == 1
        trip.vol = trip.vol - volume.batt;
        volume.batt = (spare.batt * inputs.kerbal_num * vmult.batt);
        trip.vol = trip.vol + volume.batt;
    elseif inputs.triptype == 2
        delta.batt = (spare.batt * inputs.kerbal_num * vmult.batt) - volume.batt;
        delta.fraction = (trip.vol - delta.batt) / trip.vol;
        volume.food = volume.food * delta.fraction;
        volume.water = volume.water * delta.fraction;
        volume.oxygen = volume.oxygen * delta.fraction;
        volume.nitrogen = volume.nitrogen * delta.fraction;
        volume.lioh = volume.lioh * delta.fraction;
        volume.KO3 = volume.KO3 * delta.fraction;
        volume.lox = volume.lox * delta.fraction;
        volume.lh2 = volume.lh2 * delta.fraction;
        volume.hydrogen = volume.hydrogen * delta.fraction;
        volume.liqmeth = volume.liqmeth * delta.fraction;
        volume.batt = (spare.batt * inputs.kerbal_num * vmult.batt) * vmult.batt;
        volume.waste = volume.waste * delta.fraction;
        volume.wastewater = volume.wastewater * delta.fraction;
    end
end

% the following section makes a small tank for wastewater if processes use
% it, but drain it too fast for a larger tank to be needed.

spare.wastewater = 1/4 * pk.wastewater * 24 * 3600;
if (inputs.rec == 1 || inputs.green == 1) && volume.wastewater < (spare.wastewater * inputs.kerbal_num)
    if inputs.triptype == 1
        trip.vol = trip.vol - volume.wastewater;
        volume.wastewater = spare.wastewater * inputs.kerbal_num;
        trip.vol = trip.vol + volume.wastewater;
    elseif inputs.triptype == 2
        delta.wastewater = (spare.wastewater * inputs.kerbal_num) - volume.wastewater;
        delta.fraction = (trip.volume - delta.wastewater) / trip.volume;
        volume.food = volume.food * delta.fraction;
        volume.water = volume.water * delta.fraction;
        volume.oxygen = volume.oxygen * delta.fraction;
        volume.nitrogen = volume.nitrogen * delta.fraction;
        volume.lioh = volume.lioh * delta.fraction;
        volume.KO3 = volume.KO3 * delta.fraction;
        volume.lox = volume.lox * delta.fraction;
        volume.lh2 = volume.lh2 * delta.fraction;
        volume.hydrogen = volume.hydrogen * delta.fraction;
        volume.liqmeth = volume.liqmeth * delta.fraction;
        volume.batt = volume.batt * delta.fraction;
        volume.waste = volume.waste * delta.fraction;
        volume.wastewater = spare.wastewater * inputs.kerbal_num;
    end
end

% makes a tank for waste if the incinerator fully consumes it

spare.waste = 1/4 * pk.waste * 24 * 3600;
if volume.waste < (spare.waste * inputs.kerbal_num)
    if inputs.triptype == 1
        trip.vol = trip.vol - volume.waste;
        volume.waste = spare.waste * inputs.kerbal_num;
        trip.vol = trip.vol + volume.waste;
    elseif inputs.triptype == 2
        delta.waste = (spare.waste * inputs.kerbal_num) - volume.waste;
        delta.fraction = (trip.vol - delta.waste) / trip.vol;
        volume.food = volume.food * delta.fraction;
        volume.water = volume.water * delta.fraction;
        volume.oxygen = volume.oxygen * delta.fraction;
        volume.nitrogen = volume.nitrogen * delta.fraction;
        volume.lioh = volume.lioh * delta.fraction;
        volume.KO3 = volume.KO3 * delta.fraction;
        volume.lox = volume.lox * delta.fraction;
        volume.lh2 = volume.lh2 * delta.fraction;
        volume.hydrogen = volume.hydrogen * delta.fraction;
        volume.liqmeth = volume.liqmeth * delta.fraction;
        volume.batt = volume.batt * delta.fraction;
        volume.waste = spare.waste * inputs.kerbal_num;
        volume.wastewater = volume.wastewater * delta.fraction;
    end
end

% this section creates a CO2 volume if processes exist that use it.

spare.CO2 = 1/4 * res.wasteatm * 24 * 3600;
if (inputs.moxie == 1 || inputs.green == 1)
    if inputs.triptype == 1
        volume.CO2 = spare.CO2 * inputs.kerbal_num;
        trip.vol = trip.vol + volume.CO2;
    elseif inputs.triptype == 2
        delta.CO2 = spare.CO2 * inputs.kerbal_num;
        delta.fraction = (trip.vol - delta.CO2) / trip.vol;
        volume.food = volume.food * delta.fraction;
        volume.water = volume.water * delta.fraction;
        volume.oxygen = volume.oxygen * delta.fraction;
        volume.nitrogen = volume.nitrogen * delta.fraction;
        volume.lioh = volume.lioh * delta.fraction;
        volume.KO3 = volume.KO3 * delta.fraction;
        volume.lox = volume.lox * delta.fraction;
        volume.lh2 = volume.lh2 * delta.fraction;
        volume.hydrogen = volume.hydrogen * delta.fraction;
        volume.liqmeth = volume.liqmeth * delta.fraction;
        volume.batt = volume.batt * delta.fraction;
        volume.waste = volume.waste * delta.fraction;
        volume.wastewater = volume.wastewater * delta.fraction;
        volume.CO2 = spare.CO2 * inputs.kerbal_num;
    end
else
    volume.CO2 = 0;
end

%% Launch Mass Calculations

% This section calculates the mass of each resource at launch.

mass.food = volume.food * density.food;
mass.water = volume.water * density.water;
mass.oxygen = volume.oxygen * density.oxygen / vmult.oxygen;
mass.nitrogen = volume.nitrogen * density.nitrogen / vmult.nitrogen;
mass.lioh = volume.lioh * density.lioh;
mass.KO3 = volume.KO3 * density.KO3;
mass.lox = volume.lox * density.lox;
mass.lh2 = volume.lh2 * density.lh2;
mass.hydrogen = volume.hydrogen * density.hydrogen / vmult.hydrogen;
mass.liqmeth = volume.liqmeth * density.liqmeth;
mass.batt = volume.batt * density.batt / vmult.batt;

mass.total = mass.food...
            +mass.water...
            +mass.oxygen...
            +mass.nitrogen...
            +mass.lioh...
            +mass.KO3...
            +mass.lox...
            +mass.lh2...
            +mass.hydrogen...
            +mass.liqmeth...
            +mass.batt;

%% Sanity Checks

% this section performs a volume check and warns the user if an error has
% occurred and the volumes do not sum correctly to the total volume as
% determined earlier.

trip.VolumeRatio = ( ...
                    volume.food...
                   +volume.water...
                   +volume.oxygen...
                   +volume.nitrogen...
                   +volume.lioh...
                   +volume.KO3...
                   +volume.lox...
                   +volume.lh2...
                   +volume.hydrogen...
                   +volume.liqmeth...
                   +volume.batt...
                   +volume.wastewater...
                   +volume.waste...
                   +volume.CO2...
                   ) ...
                   /trip.vol;

if round(trip.VolumeRatio) ~= 1
    warn.volerror = warndlg(["Error! Resource volume sum";"doesn't match total volume"]);
    uiwait(warn.volerror)
end

%% Output

% this section generates the graphical output displaying the resource
% amounts to be entered into real fuels.

pause(0.25)

outputs.f = figure('Name','Mission Resources',...
                   'NumberTitle','off',...
                   'units','inches',...
                   'position',[7,2,4,5]);

outputs.t1 = uicontrol('Style','text',...
                       'String','Mission Length:',...
                       'Units','inches',...
                       'HorizontalAlignment','right',...
                       'Position',[1/16,76/16,30/16,3/16]);

outputs.t2 = uicontrol('Style','text',...
                       'String','Total Volume (L):',...
                       'Units','inches',...
                       'HorizontalAlignment','right',...
                       'Position',[1/16,72/16,30/16,3/16]);

outputs.t3 = uicontrol('Style','text',...
                       'String','Food:',...
                       'Units','inches',...
                       'HorizontalAlignment','right',...
                       'Position',[1/16,68/16,30/16,3/16]);

outputs.t4 = uicontrol('Style','text',...
                       'String','Water:',...
                       'Units','inches',...
                       'HorizontalAlignment','right',...
                       'Position',[1/16,64/16,30/16,3/16]);

outputs.t5 = uicontrol('Style','text',...
                       'String','Oxygen:',...
                       'Units','inches',...
                       'HorizontalAlignment','right',...
                       'Position',[1/16,60/16,30/16,3/16]);

outputs.t6 = uicontrol('Style','text',...
                       'String','Nitrogen:',...
                       'Units','inches',...
                       'HorizontalAlignment','right',...
                       'Position',[1/16,56/16,30/16,3/16]);

outputs.t7 = uicontrol('Style','text',...
                       'String','LiOH:',...
                       'Units','inches',...
                       'HorizontalAlignment','right',...
                       'Position',[1/16,52/16,30/16,3/16]);

outputs.t8 = uicontrol('Style','text',...
                       'String','KO3:',...
                       'Units','inches',...
                       'HorizontalAlignment','right',...
                       'Position',[1/16,48/16,30/16,3/16]);

outputs.t9 = uicontrol('Style','text',...
                       'String','LOX:',...
                       'Units','inches',...
                       'HorizontalAlignment','right',...
                       'Position',[1/16,44/16,30/16,3/16]);

outputs.t10 = uicontrol('Style','text',...
                       'String','LH2:',...
                       'Units','inches',...
                       'HorizontalAlignment','right',...
                       'Position',[1/16,40/16,30/16,3/16]);

outputs.t11 = uicontrol('Style','text',...
                        'String','Hydrogen:',...
                        'Units','inches',...
                        'HorizontalAlignment','right',...
                        'Position',[1/16,36/16,30/16,3/16]);

outputs.t12 = uicontrol('Style','text',...
                        'String','Liquid Methane:',...
                        'Units','inches',...
                        'HorizontalAlignment','right',...
                        'Position',[1/16,32/16,30/16,3/16]);

outputs.t13 = uicontrol('Style','text',...
                         'String','Battery:',...
                         'Units','inches',...
                         'HorizontalAlignment','right',...
                         'Position',[1/16,28/16,30/16,3/16]);

outputs.t14 = uicontrol('Style','text',...
                         'String','Waste:',...
                         'Units','inches',...
                         'HorizontalAlignment','right',...
                         'Position',[1/16,24/16,30/16,3/16]);

outputs.t15 = uicontrol('Style','text',...
                         'String','Wastewater:',...
                         'Units','inches',...
                         'HorizontalAlignment','right',...
                         'Position',[1/16,20/16,30/16,3/16]);

outputs.t16 = uicontrol('Style','text',...
                         'String','CO2:',...
                         'Units','inches',...
                         'HorizontalAlignment','right',...
                         'Position',[1/16,16/16,30/16,3/16]);

outputs.t17 = uicontrol('Style','text',...
                         'String','Resource Total Mass:',...
                         'Units','inches',...
                         'HorizontalAlignment','right',...
                         'Position',[1/16,12/16,30/16,3/16]);

outputs.o1 = uicontrol('Style','text',...
                       'String',num2str(trip.days) + " Days",...
                       'Units','inches',...
                       'HorizontalAlignment','left',...
                       'Position',[33/16,76/16,30/16,3/16]);

outputs.o2 = uicontrol('Style','text',...
                       'String',num2str(trip.vol),...
                       'Units','inches',...
                       'HorizontalAlignment','left',...
                       'Position',[33/16,72/16,30/16,3/16]);

outputs.o3 = uicontrol('Style','text',...
                       'String',num2str(volume.food),...
                       'Units','inches',...
                       'HorizontalAlignment','left',...
                       'Position',[33/16,68/16,30/16,3/16]);

outputs.o4 = uicontrol('Style','text',...
                       'String',num2str(volume.water),...
                       'Units','inches',...
                       'HorizontalAlignment','left',...
                       'Position',[33/16,64/16,30/16,3/16]);

outputs.o5 = uicontrol('Style','text',...
                       'String',num2str(volume.oxygen / vmult.oxygen),...
                       'Units','inches',...
                       'HorizontalAlignment','left',...
                       'Position',[33/16,60/16,30/16,3/16]);

outputs.o6 = uicontrol('Style','text',...
                       'String',num2str(volume.nitrogen / vmult.nitrogen),...
                       'Units','inches',...
                       'HorizontalAlignment','left',...
                       'Position',[33/16,56/16,30/16,3/16]);

outputs.o7 = uicontrol('Style','text',...
                       'String',num2str(volume.lioh),...
                       'Units','inches',...
                       'HorizontalAlignment','left',...
                       'Position',[33/16,52/16,30/16,3/16]);

outputs.o8 = uicontrol('Style','text',...
                       'String',num2str(volume.KO3),...
                       'Units','inches',...
                       'HorizontalAlignment','left',...
                       'Position',[33/16,48/16,30/16,3/16]);

outputs.o9 = uicontrol('Style','text',...
                       'String',num2str(volume.lox),...
                       'Units','inches',...
                       'HorizontalAlignment','left',...
                       'Position',[33/16,44/16,30/16,3/16]);

outputs.o10 = uicontrol('Style','text',...
                        'String',num2str(volume.lh2),...
                        'Units','inches',...
                        'HorizontalAlignment','left',...
                        'Position',[33/16,40/16,30/16,3/16]);

outputs.o11 = uicontrol('Style','text',...
                        'String',num2str(volume.hydrogen / vmult.hydrogen),...
                        'Units','inches',...
                        'HorizontalAlignment','left',...
                        'Position',[33/16,36/16,30/16,3/16]);

outputs.o12 = uicontrol('Style','text',...
                        'String',num2str(volume.liqmeth),...
                        'Units','inches',...
                        'HorizontalAlignment','left',...
                        'Position',[33/16,32/16,30/16,3/16]);

outputs.o13 = uicontrol('Style','text',...
                        'String',num2str(volume.batt / vmult.batt) + " kJ",...
                        'Units','inches',...
                        'HorizontalAlignment','left',...
                        'Position',[33/16,28/16,30/16,3/16]);

outputs.o14 = uicontrol('Style','text',...
                        'String',num2str(volume.waste),...
                        'Units','inches',...
                        'HorizontalAlignment','left',...
                        'Position',[33/16,24/16,30/16,3/16]);

outputs.o15 = uicontrol('Style','text',...
                        'String',num2str(volume.wastewater),...
                        'Units','inches',...
                        'HorizontalAlignment','left',...
                        'Position',[33/16,20/16,30/16,3/16]);

outputs.o16 = uicontrol('Style','text',...
                        'String',num2str(volume.CO2 / vmult.CO2),...
                        'Units','inches',...
                        'HorizontalAlignment','left',...
                        'Position',[33/16,16/16,30/16,3/16]);

outputs.o16 = uicontrol('Style','text',...
                        'String',num2str(mass.total) + " Tons",...
                        'Units','inches',...
                        'HorizontalAlignment','left',...
                        'Position',[33/16,12/16,30/16,3/16]);

%% Debugger

debug.days.food = volume.food / (res.food.stable * 3600 * 24);
debug.days.water = volume.water / (res.water.stable * 3600 * 24);
debug.days.oxygen = volume.oxygen/ (res.oxygen.stable * 3600 * 24 * vmult.oxygen);
debug.days.nitrogen = volume.nitrogen / (res.nitrogen * 3600 * 24 * vmult.nitrogen);
debug.days.lioh = volume.lioh / (res.lioh * 3600 * 24);
debug.days.KO3 = volume.KO3 / (res.KO3 * 3600 * 24);
debug.days.lox = volume.lox / (res.lox.stable * 3600 * 24);
debug.days.lh2 = volume.lh2 / (res.lh2.stable * 3600 * 24);
debug.days.hydrogen = volume.hydrogen / (res.hydrogen.stable * 3600 * 24 * vmult.hydrogen);
debug.days.liqmeth = volume.liqmeth / (res.liqmeth.stable * 3600 * 24);
debug.days.batt = volume.batt / (res.batt.stable * 3600 * 24 * vmult.batt);
debug.days.wastewater = volume.wastewater / (res.wastewater.stable * 3600 * 24);
debug.days.waste = volume.waste / (res.waste * 3600 * 24);

%% Functions

function close_call(varargin)
% this function resumes the gui, allowing the values to be collected and
% the gui to be closed. It was easier to do it this way and close it in the
% main code for some reason.
    uiresume
end

function import = importreset(import)
% this function contains the default settings when import is declined.
% These are the values used in the setup gui. 0/1 are used for things like
% checkboxes, some numbers are for lists, '' is simply an empty string for
% string input boxes.
import.kerbal_num = '';
import.scrub = 1;
import.press = 1;
import.rec = 0;
import.kwrec = '';
import.showers = '';
import.green = 0;
import.kwgreen = '';
import.inc = 0;
import.kwinc = '';
import.moxie = 0;
import.kwmoxie = '';
import.elec = 0;
import.shadow = '0.27';
import.exposure = '1';
import.solar = '';
import.rtg = '';
import.nuclear = '';
import.kw = '';
import.gemini = '';
import.apollo = '';
import.aes = '';
import.soyuz = '';
import.shuttle = '';
import.ch4 = '';
import.transtime = '';
% import.decay = 0;
import.assume = 1;
import.leak = '';
import.loxgox = 0;
import.kwloxgox = '';
import.isotope = 1;
import.triptype = 1;
import.triptime = '';
import.tripvol = '';
end